repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-yaml
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ "--max-line-length=127", "--ignore=DJ01,A003" ]
        additional_dependencies: [
          flake8-comprehensions,
          flake8-print,
          flake8-simplify,
          flake8-functions,
          flake8-use-pathlib,
          flake8-fixme,
          flake8-builtins,
          pep8-naming,
          flake8-functions,
          flake8-django,
          flake8-django-migrations,
        ]
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ '-iii', '-ll' ]
#  - repo: https://github.com/ambv/black
#    rev: 23.1.0
#    hooks:
#      - id: black
