version: '3.8'

services:
  db:
    image: postgres:14.6
    container_name: todolist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 30
    restart: on-failure

  api:
    image: maximgrinin/diploma_todolist:latest
    env_file: .env
    restart: always
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy

  collect_static:
    image: maximgrinin/diploma_todolist:latest
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static/
    command: python3 manage.py collectstatic -c --no-input

  frontend:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    depends_on:
      api:
        condition: service_started
#      collect_static:
#        condition: service_completed_successfully
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

volumes:
  postgres_data:
  django_static:
