# Generated by Django 4.1.6 on 2023-03-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_tg_user_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Telegram-пользователь', 'verbose_name_plural': 'Telegram-пользователи'},
        ),
    ]
